version: "3.8"
services:
  web:
    container_name: darwin-web
    command: python3 facts.py
    working_dir: /
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./darwin:/darwin
    env_file:
      - .env
