version: "3.8"

volumes:
  node_modules: {}
  database: {}

services:
  backend:
    container_name: darwin-backend
    restart: always
    command: uvicorn web.app:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /darwin
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/darwin:/darwin
    env_file: ./backend/.env

  frontend:
    container_name: darwin-frontend
    command: npm run dev
    working_dir: /darwin
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/darwin
      - node_modules:/darwin/node_modules
    env_file: ./frontend/.env

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  # Other services...
