repos:
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.2.1
      hooks:
          - id: autoflake
            verbose: true

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
            verbose: true

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
          - id: pyupgrade
            verbose: true
            args: [--py310-plus]

    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
            verbose: true

    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
            verbose: true

    - repo: local
      hooks:
          - id: pylint
            verbose: true
            name: pylint
            entry: pylint -rn -sn
            language: system
            types: [python]

    - repo: local
      hooks:
          - id: mypy
            verbose: true
            name: mypy
            entry: mypy
            language: system
            types: [python]
